.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. pyeongtaekcoin_qt test_pyeongtaekcoin_qt
clean: FORCE
	$(MAKE) -C .. pyeongtaekcoin_qt_clean test_pyeongtaekcoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_pyeongtaekcoin_qt_check
pyeongtaekcoin-qt pyeongtaekcoin-qt.exe: FORCE
	 $(MAKE) -C .. pyeongtaekcoin_qt
